language: cpp
sudo: required
compiler:
- g++
dist: xenial
addons:
  apt:
    packages:
    - gdb
    - make
    - git
    - bison
    - flex
    - g++-mips-linux-gnu
    - gdb-multiarch
    - qemu

before_install:
- echo $LANG
- echo $LC_ALL
- chmod u+x ./scripts/dependencies.sh
- ./scripts/dependencies.sh
script:
- ./scripts/testansi.sh
- ./scripts/testmips.sh
branches:
  only:
    - master
    - ast2mips
